export const mockBD = [
  {
    id: 1,
    title: "Бургерная на краю вселенной",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae ratione quam ut corrupti reprehenderit tempora, minima tenetur doloremque, animi ad distinctio error veritatis sapiente corporis deleniti quo quis temporibus id! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique aspernatur autem quae neque, provident aliquid, dolores debitis culpa architecto quia, sapiente tempora suscipit perspiciatis optio obcaecati maxime aperiam modi cumque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maiores obcaecati odio officia laborum fuga iusto beatae culpa nulla error. Porro ullam dolorem consequatur exercitationem sunt soluta nulla eligendi minima!",
    imageUrl: "",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "javascript ", imgUrl: "https://skillicons.dev/icons?i=js" },
      { title: "typescript ", imgUrl: "https://skillicons.dev/icons?i=ts" },
      { title: "react ", imgUrl: "https://skillicons.dev/icons?i=react" },
      { title: "next ", imgUrl: "https://skillicons.dev/icons?i=nextjs" },
    ],
  },
  {
    id: 2,
    title: "Справочник зананий 'Транзит'",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae ratione quam ut corrupti reprehenderit tempora, minima tenetur doloremque, animi ad distinctio error veritatis sapiente corporis deleniti quo quis temporibus id! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique aspernatur autem quae neque, provident aliquid, dolores debitis culpa architecto quia, sapiente tempora suscipit perspiciatis optio obcaecati maxime aperiam modi cumque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maiores obcaecati odio officia laborum fuga iusto beatae culpa nulla error. Porro ullam dolorem consequatur exercitationem sunt soluta nulla eligendi minima!",
    imageUrl: "",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "javascript", imgUrl: "https://skillicons.dev/icons?i=js" },
      { title: "typescript", imgUrl: "https://skillicons.dev/icons?i=ts" },
      { title: "react", imgUrl: "https://skillicons.dev/icons?i=react" },
      { title: "next", imgUrl: "https://skillicons.dev/icons?i=nextjs" },
    ],
  },
  {
    id: 3,
    title: "Волжские огни",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae ratione quam ut corrupti reprehenderit tempora, minima tenetur doloremque, animi ad distinctio error veritatis sapiente corporis deleniti quo quis temporibus id! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique aspernatur autem quae neque, provident aliquid, dolores debitis culpa architecto quia, sapiente tempora suscipit perspiciatis optio obcaecati maxime aperiam modi cumque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maiores obcaecati odio officia laborum fuga iusto beatae culpa nulla error. Porro ullam dolorem consequatur exercitationem sunt soluta nulla eligendi minima!",
    imageUrl: "",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "HTML", imgUrl: "https://skillicons.dev/icons?i=js" },
      { title: "Bootstrap", imgUrl: "https://skillicons.dev/icons?i=ts" },
      { title: "Sass", imgUrl: "https://skillicons.dev/icons?i=react" },
    ],
  },
  {
    id: 4,
    title: "Бургерная на краю вселенной",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae ratione quam ut corrupti reprehenderit tempora, minima tenetur doloremque, animi ad distinctio error veritatis sapiente corporis deleniti quo quis temporibus id! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique aspernatur autem quae neque, provident aliquid, dolores debitis culpa architecto quia, sapiente tempora suscipit perspiciatis optio obcaecati maxime aperiam modi cumque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maiores obcaecati odio officia laborum fuga iusto beatae culpa nulla error. Porro ullam dolorem consequatur exercitationem sunt soluta nulla eligendi minima!",
    imageUrl: "",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "javascript", imgUrl: "https://skillicons.dev/icons?i=js" },
      { title: "typescript", imgUrl: "https://skillicons.dev/icons?i=ts" },
      { title: "react", imgUrl: "https://skillicons.dev/icons?i=react" },
      { title: "next", imgUrl: "https://skillicons.dev/icons?i=nextjs" },
    ],
  },
  {
    id: 5,
    title: "title 5",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae ratione quam ut corrupti reprehenderit tempora, minima tenetur doloremque, animi ad distinctio error veritatis sapiente corporis deleniti quo quis temporibus id! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique aspernatur autem quae neque, provident aliquid, dolores debitis culpa architecto quia, sapiente tempora suscipit perspiciatis optio obcaecati maxime aperiam modi cumque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maiores obcaecati odio officia laborum fuga iusto beatae culpa nulla error. Porro ullam dolorem consequatur exercitationem sunt soluta nulla eligendi minima!",
    imageUrl: "",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "javascript", imgUrl: "https://skillicons.dev/icons?i=js" },
      { title: "typescript", imgUrl: "https://skillicons.dev/icons?i=ts" },
      { title: "react", imgUrl: "https://skillicons.dev/icons?i=react" },
      { title: "next", imgUrl: "https://skillicons.dev/icons?i=nextjs" },
    ],
  },
  {
    id: 6,
    title: "title 6",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vitae ratione quam ut corrupti reprehenderit tempora, minima tenetur doloremque, animi ad distinctio error veritatis sapiente corporis deleniti quo quis temporibus id! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Similique aspernatur autem quae neque, provident aliquid, dolores debitis culpa architecto quia, sapiente tempora suscipit perspiciatis optio obcaecati maxime aperiam modi cumque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maiores obcaecati odio officia laborum fuga iusto beatae culpa nulla error. Porro ullam dolorem consequatur exercitationem sunt soluta nulla eligendi minima!",
    imageUrl: "",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "javascript", imgUrl: "https://skillicons.dev/icons?i=js" },
      { title: "typescript", imgUrl: "https://skillicons.dev/icons?i=ts" },
      { title: "react", imgUrl: "https://skillicons.dev/icons?i=react" },
      { title: "next", imgUrl: "https://skillicons.dev/icons?i=nextjs" },
    ],
  },
]
