export const mockBD = [
  {
    id: 1,
    title: "Бургерная на краю вселенной",
    body: "Учебный проект курса React-разработчик от школы Яндекс.Практикум. ",
    imageUrl: "/projectsImages/StellarBurger.png",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "javascript ", imgUrl: "icons/JavaScript.svg" },
      { title: "typescript ", imgUrl: "icons/TypeScript.svg" },
      { title: "react ", imgUrl: "/icons/React.svg" },
      { title: "tailwind ", imgUrl: "icons/Tailwind.svg" },
      { title: "redux ", imgUrl: "icons/Redux.svg" },
      { title: "supabase ", imgUrl: "icons/Supabase.svg" },
    ],
  },
  {
    id: 2,
    title: "Справочник зананий для сотрудников компании Транзит",
    body: "Веб справочник для сотрудников компании Транзит, изначально предназначался для помощи в самостоятельном изучении стажёров компании, и хранилище знаничй об особенностях микроавтобусов Форд Транзит, Пежо Бокстер, Ситроен Джампер",
    imageUrl: "/projectsImages/TransitHandbook.png",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "javascript ", imgUrl: "icons/JavaScript.svg" },
      { title: "typescript ", imgUrl: "icons/TypeScript.svg" },
      { title: "react ", imgUrl: "/icons/React.svg" },
      { title: "redux ", imgUrl: "icons/Redux.svg" },
      { title: "tailwind ", imgUrl: "icons/Tailwind.svg" },
      { title: "supabase ", imgUrl: "icons/Supabase.svg" },
    ],
  },
  {
    id: 3,
    title: "Волжские огни",
    body: "Сайт таксомоторной компании 'Волжские огни', принимал участие в проекте как верстальщик",
    imageUrl: "/projectsImages/VolgaLights.png",
    ginhubUrl: "https://github.com",
    stack: [
      { title: "html ", imgUrl: "icons/HTML.svg" },
      { title: "sass ", imgUrl: "icons/Sass.svg" },
      { title: "bootstrap ", imgUrl: "/icons/Bootstrap.svg" },
      { title: "gulp ", imgUrl: "icons/Gulp.svg" },
    ],
  },
]
